# Generated by Django 5.0.2 on 2024-03-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
        ('Wallet', '0002_wallet_remove_walletmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Wallet.wallet'),
        ),
    ]
