# Generated by Django 5.0.2 on 2024-03-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_alter_transactionmodel_wallet'),
        ('Wallet', '0002_wallet_remove_walletmodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletModel',
        ),
    ]
